version: 2

jobs:
  build:
    working_directory: ~/paymentapp
    docker:
      - image: circleci/node:8
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      
      - run: npm install

      - save_cache:
          paths: 
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }} 
      
      - run: 
          name: jest tests
          command: |
            mkdir -p test-results/jest
            npm test
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml
      
      - persist_to_workspace:
          root: ~/paymentapp
          paths:
            - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results


workflows:
  version: 2
  builds:
    jobs:
      - build