export const authActions = {
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  AUTHENTICATION_SUCCESS: 'AUTHENTICATION_SUCCESS',
  AUTHENTICATION_FAILURE: 'REQUEST_FAILURE',
};

export const userActions = {
  GET_SELF_INFO: 'GET_SELF_INFO',
  GET_SELF_INFO_SUCCESS: 'GET_SELF_INFO_SUCCESS',
  GET_USER_INFO: 'GET_USER_INFO',
  GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_IMAGE: 'UPDATE_IMAGE',
  UPDATE_IMAGE_SUCCESS: 'UPDATE_IMAGE_SUCCESS',
  REQUEST_FAILURE: 'REQUEST_FAILURE',
};

export const projectActions = {
  ADD_PROJECT: 'ADD_PROJECT',
  ADD_PROJECT_SUCCESS: 'ADD_PROJECT_SUCCESS',
  ADD_PROJECT_FAILURE: 'ADD_PROJECT_FAILURE',
  GET_PROJECTS: 'GET_PROJECTS',
  GET_PROJECTS_SUCCESS: 'GET_PROJECTS_SUCCESS',
  GET_PROJECTS_FAILURE: 'GET_PROJECTS_FAILURE',
};

export const taskActions = {
  ADD_TASK: 'ADD_TASK',
  ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
  ADD_TASK_FAILURE: 'ADD_TASK_FAILURE',
  GET_TASKS: 'GET_TASKS',
  GET_TASKS_SUCCESS: 'GET_TASKS_SUCCESS',
  GET_TASKS_FAILURE: 'GET_TASKS_FAILURE',
  SET_CURRENT_PROJECT: 'SET_CURRENT_PROJECT',
};
