export const authActions = {
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  AUTHENTICATION_SUCCESS: 'AUTHENTICATION_SUCCESS',
  AUTHENTICATION_FAILURE: 'REQUEST_FAILURE',
};

export const userActions = {
  GET_SELF_INFO: 'GET_SELF_INFO',
  GET_USER_INFO: 'GET_USER_INFO',
  UPDATE_USER: 'UPDATE_USER',
  GET_SELF_INFO_SUCCESS: 'GET_SELF_INFO_SUCCESS',
  GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  REQUEST_FAILURE: 'REQUEST_FAILURE',
};